name: Build Racing Aid

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build -c Release

    - name: Publish the project
      run: dotnet publish ./RacingAidWpf/RacingAidWpf.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o out

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: RacingAid-Exe
        path: out/ # The path where the .exe is located
